name: project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  phosphor_flutter: ^1.4.0
  table_calendar: ^3.0.7
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.2
  google_sign_in: ^5.4.2
  image_picker: ^0.8.6
  jiffy: ^5.0.0
  animated_toggle_switch: ^0.5.2
  flutter_riverpod: ^2.1.1
  shared_preferences: ^2.0.15
  settings_ui: ^2.0.2
  flutter_dotenv: ^5.0.2
  flutter_staggered_grid_view: ^0.6.2
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6
  path: ^1.8.2
  http: ^0.13.5
  flutter_facebook_auth: ^5.0.6
  flutter_colorpicker: ^1.0.3
  rxdart: ^0.27.7
  xor_cipher: ^1.0.0+1
  github_sign_in: ^0.0.5-dev.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - variables.env

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
